// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqA6kYQg-lEwojjxm4v0KX0KgX4WIONMQ',
    appId: '1:887084066236:android:253396e99c3d98273e77b9',
    messagingSenderId: '887084066236',
    projectId: 'clima-a258c',
    storageBucket: 'clima-a258c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-4PVkqyZIUadFdXfNh-5Z8D6OJQnpaD0',
    appId: '1:887084066236:ios:2cdf3b9b176d3b4b3e77b9',
    messagingSenderId: '887084066236',
    projectId: 'clima-a258c',
    storageBucket: 'clima-a258c.firebasestorage.app',
    iosBundleId: 'com.alfredopalacios.climaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFJIh13fEBANfgKHHCXURGGmSaVpY-MxI',
    appId: '1:887084066236:web:3a5b85080e873b0c3e77b9',
    messagingSenderId: '887084066236',
    projectId: 'clima-a258c',
    authDomain: 'clima-a258c.firebaseapp.com',
    storageBucket: 'clima-a258c.firebasestorage.app',
    measurementId: 'G-HXN5BXMFWW',
  );

}